Finished CRUD for Clients REST API
marcosb74/RESTAPINicolas pull request #3
Opened 2023-06-13 23:04 UTC by NicolasU94

Created Clientes model and defined routes and controller methods to complete REST API CRUD.

2023-06-14 23:50 UTC, marcosb74 commented on controller/clienteController.js
> +    next();
que hace next?

2023-06-14 23:50 UTC, marcosb74 commented on controller/clienteController.js
> +    res.json(clients);
esto no va a andar

2023-06-14 23:50 UTC, marcosb74 commented on controller/clienteController.js
> +    res.json(clients);
la linea de abajo me refiero

2023-06-14 23:51 UTC, marcosb74 commented on controller/clienteController.js
> +    next();
nuevamente, que hace este next aca ?

2023-06-14 23:51 UTC, marcosb74 commented on controller/clienteController.js
> +//deleteClientById
comment

2023-06-14 23:52 UTC, marcosb74 commented on index.js
> +mongoose.connect("mongodb://localhost/restapi", {
como pondrias el mongodb://localhost/restapi en el .env? Podes hacerlo ?

2023-06-14 23:52 UTC, marcosb74 requested changes
Explicame los comments o hace lo que te pedi y avisame por discord. No avances hasta que lo hayas corregido / defendido conmigo.

2023-06-15 00:20 UTC, NicolasU94 commented on index.js
> +mongoose.connect("mongodb://localhost/restapi", {
Se puede hacer

2023-06-15 00:21 UTC, NicolasU94 commented on controller/clienteController.js
> +    next();
Me olvide de sacarlo no va porque me rompe el codigo.

2023-06-15 00:22 UTC, NicolasU94 commented on controller/clienteController.js
> +    next();
Ahora lo saco

2023-06-15 02:33 UTC, marcosb74 commented on index.js
> +app.listen(process.env.PORT);
esta mal esto

2023-06-15 02:34 UTC, marcosb74 commented on index.js
> +
const port = process.env.PORT || 5000

2023-06-15 02:34 UTC, marcosb74 commented on index.js
> +app.listen(process.env.PORT);
y aca usas port.

2023-06-15 02:37 UTC, marcosb74 approved these changes

2023-06-15 02:53 UTC, merged